#!/usr/bin/env python2

import requests as rq
import sys
import json
# import getch
import tty
import termios
speed = "no"

fd = sys.stdin.fileno()
old_settings = termios.tcgetattr(fd)

def exit():
	termios.tcsetattr(fd, termios.TCSADRAIN, old_settings)
	sys.exit()

def send(command):
	res = rq.post("http://192.168.1.31:38080",data=json.dumps({"Command":command}))
	#print res.text
def stop():
	send("stop")
def forward():
		global speed
		send(speed + "fo")
def backward():
	global speed
	send(speed + "ba")
def turnleft():
	global speed
	send(speed + "le")
def turnright():
	global speed
	send(speed + "ri")


if __name__ == "__main__":
	print """
		Usage:
		 ./test
			w : forward
			s : backward
			a : turnleft
			d : turnright
			q : normal speed
			e : high speed
			z : exit program
		   others : stop
		"""
	while True:
		tty.setraw(sys.stdin.fileno())
		inputs = sys.stdin.read(1)
		if inputs == "w": forward()
		elif inputs == 's': backward()
		elif inputs == 'a': turnleft()
		elif inputs == 'd': turnright()
		elif inputs == 'q': speed = "no"
		elif inputs == 'e': speed = "hi"
		elif inputs == 'z': sys.exit()
		else: stop()


